apiVersion: v1
kind: Service
metadata:
  name: authentication-document
spec:
  selector:
    app.kubernetes.io/name: authentication-document
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081


---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    autopilot.gke.io/resource-adjustment: >-
      {"input":{"containers":[{"name":"authentication-document"}]},"output":{"containers":[{"limits":{"cpu":"500m","ephemeral-storage":"1Gi","memory":"2Gi"},"requests":{"cpu":"500m","ephemeral-storage":"1Gi","memory":"2Gi"},"name":"authentication-document"}]},"modified":true}
    autopilot.gke.io/warden-version: 2.7.41
  labels:
    app: authentication-document
  name: authentication-document
  namespace: microservicios-distribuidas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication-document
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: authentication-document
    spec:
      containers:
        - image: gcr.io/hazel-champion-399821/github.com/jescobar2/authentication-document
          imagePullPolicy: IfNotPresent
          name: authentication-document
          resources:
            limits:
              cpu: 500m
              ephemeral-storage: 1Gi
              memory: 128Mi
            requests:
              cpu: 250m
              ephemeral-storage: 1Gi
              memory: 64Mi
          securityContext:
            capabilities:
              drop:
                - NET_RAW
          env:
            - name: RABBITMQ_HOST
              value: rabbitmq-service
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      tolerations:
        - effect: NoSchedule
          key: kubernetes.io/arch
          operator: Equal
          value: amd64

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: authentication-document
  namespace: microservicios-distribuidas
spec:
  maxReplicas: 5
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 80
          type: Utilization
      type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: authentication-document
